### ISSUE TITLE
Add custom buffers by disturbance type

### ISSUE THREAD

**Issue by edwardsmarc** [beaconsproject/disturbance_explorer#5]
* Add "Use custom buffer" button. 
  * If clicked, open modal that contains a switch between custom and universal buffer.
    * If custom, allow values to be specified in a table, grey out slider.
    * If universal, grey out table and open slider.
    * Keep custom table stored so if it gets re-activated the values are not lost.

**Comment by prvernier** [comment]
This looks great! Can we make it so only disturbance types that occur in the current FDA are listed?

**Comment by edwardsmarc** [comment]
It should be doing that already. It compiles the list from the linear() and area() objects which are the loaded FDA vector files.

**Comment by prvernier** [comment]
Ok, yes I see that now. I was just counting the number of rows in each table. The problem is that there are several Disturbance types that occur across several Industry types e.g., Access Road is listed under Mining, Transportation and Unknown. I wonder if we should only list disturbance types and drop the industry column. Otherwise that would be a lot of data entry and I don't think users would want to have different buffer sizes for the same type.

**Comment by edwardsmarc** [comment]
I was thinking users might want to give a different buffer to a mining access road compared to say, a backcountry hunting access road which would get a lot less traffic. I'm happy to consolidate, but we should also consider that anyone wanting to assign custom buffers might want access to all attribute combinations.

I was originally looking for a way to do this hierarchically. So you could easily assign all mining a given value. But then I found the excel table widget which is fast to edit and everyone is familiar with. We should make it sortable, I'll add an issue for that.

**Comment by prvernier** [comment]
Ok, good points. Let's leave it all in - maximum flexibility!
